### PR TITLE
revert(#434): use getSlidesVNodes utility to extract slides to be clone

### LINKED ISSUE #442: Cloned Slides Not Rendered Correctly
After merging [PR #434](https://github.com/ismail9k/vue3-carousel/pull/434/files), the cloned slides are not rendered correctly. This issue can be observed in the [Wrap Around example](https://vue3-carousel.ismail9k.com/examples-fallback.html#wrap-around).

Steps to Reproduce:
	1.	Visit the [Wrap Around example](https://vue3-carousel.ismail9k.com/examples-fallback.html#wrap-around).
	2.	Observe how the cloned slides are not displayed as expected.

Expected Behavior:
The cloned slides should render properly, maintaining the carousel’s functionality and appearance.

Actual Behavior:
The cloned slides are missing or incorrectly displayed, affecting the carousel’s wrap-around behavior.

### PR DESCRIPTION
**Pull request by ismail9k**
The change was found to cause issues during static site generation processes, particularly with frameworks like VitePress.
 
By reverting this, we restore compatibility with static file generation workflows while maintaining functionality for existing use cases.

Closes #442

### CODE REVIEW

**Comment by ismail9k** [comment]
Could you please review this PR @Tofandel?

**Comment by Tofandel** [comment]
Did you check that this would solve it? It looks to be more of a SSR issue, where the generated stuff SSR does not match what is generated on mounted, I highly doubt this would fix this

**Comment by Tofandel** [comment]
From what I see the cloned vNodes are not rendering properly SSR (before mount), they are comments

image

And because vue's hydration policy dictates that hydration mismatch should not update, they do not get mounted after that

**Comment by Tofandel** [comment]
Temporarily I think we should disable the cloned vNode until the mount action which would solve the hydration mismatch issue

**Comment by ismail9k** [comment]
Yes, this solution resolves the issue. You can verify it by building the documentation, as the problem occurs specifically during the build process.

I don’t believe that disabling clones until the component is mounted would address the issue. From my observations, the carousel goes through two rendering phases:
	1.	Initial render: The slides are displayed without clones because they haven’t been registered yet.
	2.	Second render: The cloned slides are added after registration.

Since VitePress processes the HTML markup during static site generation, it only captures the initial render, which excludes the cloned slides. This discrepancy leads to the problem during build time.

**Comment by Tofandel** [comment]
The problem with getSlidesVnodes was that it was not working properly with Slides passed through a slot

I implemented a proper fix in #444

**Comment by ismail9k** [comment]
Closed in favor of #444

**Pull request closed without merging**
