### PR TITLE
Add optionaly css class to hide in active navigation arrows

### PR DESCRIPTION
**Pull request by radzikowski**

### CODE REVIEW

**Comment by ismail9k** [comment]
Thank you for your contribution

**Comment by radzikowski** [comment]
Hi @ismail9k take a look at your releases procedure make,  please - fetching from npm registry, make tags etc, because I don't see this code on new release (you also don't have a tag for new release, last is 0.1.31), whilst all chances are on master branch.

**Comment by ismail9k** [comment]
I have releasesd a new version, could you check

**Comment by radzikowski** [comment]
> I have releasesd a new version, could you check

Yes, everything is correct now. Thanks.

**Pull request merged**
